# Generated by Django 4.1.6 on 2023-02-13 12:21

from django.db import migrations

roles = ['superAdmin', 'merchantOwner', 'user']


def add_roles(apps, schema_editor):
    """
    Migration code to add roles
    :param apps:
    :param schema_editor:
    :return:
    """
    Role = apps.get_model('users', 'Role')
    role_objects = [Role(name=role) for role in roles]
    Role.objects.bulk_create(role_objects)


def reverse_code(apps, schema_editor):
    """
    Reverse migration code
    :param apps:
    :param schema_editor:
    :return:
    """
    Role = apps.get_model('users', 'Role')
    Role.objects.filter(name__in=roles).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_roles, reverse_code=reverse_code)
    ]
