# Generated by Django 4.1.6 on 2023-02-15 11:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expire_at',
            field=models.DateField(default=datetime.date(2023, 2, 22)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
