# Generated by Django 4.1.6 on 2023-02-14 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitemprice',
            name='title',
        ),
    ]
