# Generated by Django 4.1.6 on 2023-02-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('aggregator_order_id', models.CharField(max_length=100, unique=True)),
                ('order_placed', models.DateTimeField(null=True)),
                ('aggregator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.aggregator')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='inventory.store')),
            ],
            options={
                'db_table': 'order',
                'unique_together': {('aggregator', 'aggregator_order_id')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storeitemprice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
            ],
            options={
                'db_table': 'orderItem',
            },
        ),
    ]
